// packages/db/src/repositories/claim.repository.ts
//
// the spec/p.18 (P10 Attribution). Two writes for one "file a claim"
// user action — `create` (FILED) then `markScored` (FILED -> SCORED) —
// called together inside one apps/api transaction, same "one API call,
// multiple individually-validated internal hops" precedent as Lockbox's
// `release()` cascade (earlier). Unlike Lockbox's DRAFT (truly never
// persisted), FILED here IS a real, briefly-persisted row — richer audit
// trail (a claim.filed event distinct from claim.scored) for a step
// (scoring) more complex/worth-separately-auditing than a single crypto
// call. See @tol/domain/src/claim-states.ts's header comment.

import type { Claim, ClaimStatus, DirectnessTier, DisclosureClass, SourceType } from "@prisma/client";
import { newId } from "../ids.js";
import { assertJsonSafePlainObject, assertStringArray } from "../json-guards.js";
import type { DbClient } from "./types.js";

export interface CreateFiledClaimInput {
  id: string; // generated by the caller (apps/api's service), same convention as newLockboxId()
  claimantOrgId: string;
  claimantUserId: string;
  subjectOrgId: string;
  relationshipType: string;
  directnessTier: DirectnessTier;
  opportunityId?: string | null;
  claimScope: object;
  priorCommercialHistoryMonths: number;
  submissionLagDays: number;
  privacyClass?: DisclosureClass;
  createdByUserId?: string | null;
  createdByOrgId?: string | null;
  sourceType?: SourceType;
  sourceReference?: string | null;
}

export interface MarkClaimScoredInput {
  scoreBreakdown: object;
  scoreTotal: number;
  algorithmVersion: string;
  inputVersions: readonly string[];
  scoredAt: Date;
  provisionalExpiresAt: Date | null;
  updatedByUserId: string | null;
}

export const claimRepository = {
  async findById(db: DbClient, id: string): Promise<Claim | null> {
    return db.claim.findUnique({ where: { id } });
  },

  /** The claimant's own "my claims" list. */
  async listByClaimant(db: DbClient, claimantOrgId: string): Promise<Claim[]> {
    return db.claim.findMany({ where: { claimantOrgId }, orderBy: { createdAt: "desc" } });
  },

  /**
   * Competing claims about the same relationship — grouped by
   * (subjectOrgId, opportunityId), see schema.prisma's Claim comment on
   * why this replaces a shared relationshipId foreign key
   * (ADR-0010). `opportunityId: null` matches claims scoped
   * BROADER than one opportunity (a whole program/geography claim), not
   * "any opportunity" — same explicit-null-means-null discipline as
   * every other optional FK filter in this codebase.
   *
   * `take: 500` — a defensive cap, not a real pagination story (review, correctly noted
   * this call had no limit at all). Realistic competing-claim counts for
   * one relationship are single/low-double digits; 500 is generous
   * headroom against a pathological case without silently truncating any
   * plausible real one.
   */
  async listBySubject(db: DbClient, subjectOrgId: string, opportunityId: string | null): Promise<Claim[]> {
    return db.claim.findMany({
      where: { subjectOrgId, opportunityId },
      orderBy: { createdAt: "asc" }, // ascending — @tol/attribution's rankClaims does its own descending-score sort; this just gives a stable base order (earliest-filed first) for it to work from.
      take: 500,
    });
  },

  /** Cross-org listing (operator/compliance/auditor) — every Claim, newest first. */
  async list(db: DbClient, opts: { limit?: number } = {}): Promise<Claim[]> {
    return db.claim.findMany({ take: opts.limit ?? 100, orderBy: { createdAt: "desc" } });
  },

  /** Filing is the first write — always at status FILED, score fields left null (set by markScored, inside the same transaction, immediately after). */
  async create(db: DbClient, input: CreateFiledClaimInput): Promise<Claim> {
    assertJsonSafePlainObject(input.claimScope, "claimScope");
    return db.claim.create({
      data: {
        id: input.id,
        claimantOrgId: input.claimantOrgId,
        claimantUserId: input.claimantUserId,
        subjectOrgId: input.subjectOrgId,
        relationshipType: input.relationshipType,
        directnessTier: input.directnessTier,
        opportunityId: input.opportunityId ?? null,
        claimScope: input.claimScope as object,
        status: "FILED",
        priorCommercialHistoryMonths: input.priorCommercialHistoryMonths,
        submissionLagDays: input.submissionLagDays,
        privacyClass: input.privacyClass ?? "RESTRICTED",
        createdByUserId: input.createdByUserId ?? null,
        createdByOrgId: input.createdByOrgId ?? null,
        sourceType: input.sourceType ?? "PLATFORM",
        sourceReference: input.sourceReference ?? null,
      },
    });
  },

  /** FILED -> SCORED, with the @tol/attribution breakdown persisted in the same write. Callers run @tol/domain's assertValidClaimTransition first. */
  async markScored(db: DbClient, id: string, input: MarkClaimScoredInput): Promise<Claim> {
    assertJsonSafePlainObject(input.scoreBreakdown, "scoreBreakdown");
    assertStringArray(input.inputVersions as unknown, "inputVersions");
    return db.claim.update({
      where: { id },
      data: {
        status: "SCORED",
        scoreBreakdown: input.scoreBreakdown as object,
        scoreTotal: input.scoreTotal,
        algorithmVersion: input.algorithmVersion,
        inputVersions: [...input.inputVersions],
        scoredAt: input.scoredAt,
        provisionalExpiresAt: input.provisionalExpiresAt,
        updatedByUserId: input.updatedByUserId,
        version: { increment: 1 },
      },
    });
  },

  /** Generic status-only transition — VERIFIED/PARTIAL/REJECTED/DISPUTED/EXPIRED/WITHDRAWN, all reachable this way (unlike scoring, none of these carry extra columns beyond status itself). Callers run assertValidClaimTransition first — same division of labor as lockboxRepository.updateStatus. */
  async updateStatus(db: DbClient, id: string, status: ClaimStatus, updatedByUserId: string | null): Promise<Claim> {
    return db.claim.update({
      where: { id },
      data: { status, updatedByUserId, version: { increment: 1 } },
    });
  },
};

/** Id helper re-exported so apps/api's service can generate the id up front (matches newLockboxId's precedent) without importing ../ids.js directly (deep-import discipline, the spec). */
export function newClaimId(): string {
  return newId();
}
