// packages/db/src/repositories/lockbox.repository.ts
//
// the spec. Note the Prisma client accessor is `db.lockbox` (plain
// camelCase — "Lockbox" isn't an all-caps acronym like "RFQ", so it
// doesn't hit the same casing gotcha rfq.repository.ts documents).

import type { DisclosureClass, Lockbox, LockboxRegion, LockboxRelationshipType, LockboxStatus, SourceType } from "@prisma/client";
import { newId } from "../ids.js";
import { toBytesInput, toBytesInputOrNull, type DbClient } from "./types.js";

export interface CreateSealedLockboxInput {
  id: string; // generated by the caller (apps/api's service) BEFORE this call, since the same id is used as AES-GCM's AAD at encryption time — see schema.prisma's Lockbox.aad comment.
  sealerOrgId: string;
  relationshipType: LockboxRelationshipType;
  region: LockboxRegion;
  metadataSummary?: string | null;
  iv: Buffer;
  ciphertext: Buffer;
  authTag: Buffer;
  aad?: Buffer | null;
  ciphertextHash: string;
  sealedAt: Date;
  privacyClass?: DisclosureClass;
  createdByUserId?: string | null;
  createdByOrgId?: string | null;
  sourceType?: SourceType;
  sourceReference?: string | null;
}

export const lockboxRepository = {
  async findById(db: DbClient, id: string): Promise<Lockbox | null> {
    return db.lockbox.findUnique({ where: { id } });
  },

  /** The sealer's own "my lockboxes" list. */
  async listBySealer(db: DbClient, sealerOrgId: string): Promise<Lockbox[]> {
    return db.lockbox.findMany({ where: { sealerOrgId }, orderBy: { createdAt: "desc" } });
  },

  /** Cross-org listing (operator/compliance/auditor) — every Lockbox, newest first. Callers project this down to the market-visible fields (existence/type/region/status only) at the mapper layer — this repository function itself returns full rows including ciphertext, matching every other repository's "repositories are persistence-thin, filtering is a service/mapper concern" convention. */
  async list(db: DbClient, opts: { limit?: number } = {}): Promise<Lockbox[]> {
    return db.lockbox.findMany({ take: opts.limit ?? 100, orderBy: { createdAt: "desc" } });
  },

  /** Sealing is the one action that creates a Lockbox row — always already at status SEALED (there is no persisted DRAFT row; see @tol/domain/src/lockbox-states.ts's header comment). */
  async createSealed(db: DbClient, input: CreateSealedLockboxInput): Promise<Lockbox> {
    return db.lockbox.create({
      data: {
        id: input.id,
        sealerOrgId: input.sealerOrgId,
        relationshipType: input.relationshipType,
        region: input.region,
        status: "SEALED",
        metadataSummary: input.metadataSummary ?? null,
        iv: toBytesInput(input.iv),
        ciphertext: toBytesInput(input.ciphertext),
        authTag: toBytesInput(input.authTag),
        aad: toBytesInputOrNull(input.aad),
        ciphertextHash: input.ciphertextHash,
        sealedAt: input.sealedAt,
        privacyClass: input.privacyClass ?? "SECRET",
        createdByUserId: input.createdByUserId ?? null,
        createdByOrgId: input.createdByOrgId ?? null,
        sourceType: input.sourceType ?? "PLATFORM",
        sourceReference: input.sourceReference ?? null,
      },
    });
  },

  /** Status-only transition — see @tol/domain's assertValidLockboxTransition, which callers run BEFORE this. Used for the intermediate hops of the release cascade (SEALED -> COMMITTED -> FROZEN) that don't carry their own extra columns to set. */
  async updateStatus(db: DbClient, id: string, status: LockboxStatus, updatedByUserId: string | null): Promise<Lockbox> {
    return db.lockbox.update({
      where: { id },
      data: { status, updatedByUserId, version: { increment: 1 } },
    });
  },

  /** Withdraw: SEALED (or any of the other withdrawable states — see @tol/domain's canWithdrawFrom) -> WITHDRAWN, with the withdraw metadata columns set in the same write. Callers run assertValidLockboxTransition first. */
  async withdraw(
    db: DbClient,
    id: string,
    input: { withdrawnAt: Date; withdrawnByUserId: string; withdrawReason: string | null },
  ): Promise<Lockbox> {
    return db.lockbox.update({
      where: { id },
      data: {
        status: "WITHDRAWN",
        withdrawnAt: input.withdrawnAt,
        withdrawnByUserId: input.withdrawnByUserId,
        withdrawReason: input.withdrawReason,
        updatedByUserId: input.withdrawnByUserId,
        version: { increment: 1 },
      },
    });
  },

  /** Release's terminal hop (FROZEN -> OPENED), with the release metadata columns set in the same write as the final status change. The intermediate SEALED -> COMMITTED -> FROZEN hops go through updateStatus above, inside the same transaction — see apps/api's lockbox service for the full cascade. */
  async markOpened(
    db: DbClient,
    id: string,
    input: { releasedAt: Date; recipientOrgId: string; conditionRef: string; updatedByUserId: string },
  ): Promise<Lockbox> {
    return db.lockbox.update({
      where: { id },
      data: {
        status: "OPENED",
        releasedAt: input.releasedAt,
        recipientOrgId: input.recipientOrgId,
        conditionRef: input.conditionRef,
        updatedByUserId: input.updatedByUserId,
        version: { increment: 1 },
      },
    });
  },
};

/** Id helper re-exported so apps/api's service can generate the id up front (needed for AAD, see CreateSealedLockboxInput's comment) without importing ../ids.js directly (deep-import discipline, the spec). */
export function newLockboxId(): string {
  return newId();
}
